//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accommodation_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int ProId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public int RoomNumber { get; set; }
        public int RentPrice { get; set; }
        public bool isFurnished { get; set; }
        public bool isApproved { get; set; }
        public System.DateTime AvailableDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Address { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Photo { get; set; }
        public string UAOComment { get; set; }
    }
}
